name: orifice
author: Yogesh Maheshwari
description: Using bernoulli experiment to work with SpriteSheets
dependencies:
  browser: any
  stagexl: any
  stagexl_bitmapfont: any
  stagexl_flump: any
  stagexl_richtextfield: any
  stagexl_spine: any
transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives", "--dump-info"]
    minify: true
